local strings = {
    [SI_BAV_PANEL_NAME] = "Bureau of Acceptable Views",
    [SI_BAV_PANEL_DISPLAY_NAME] = "|c6FCB9FBureau|r of Acceptable Views",
    [SI_BAV_PANEL_DESCRIPTION] = "Аккуратно расширяет управление камерой в ограниченных состояниях, улучшает возврат из вида от первого лица и даёт гибкие настройки сохранения зума. Ввод с контроллера обрабатывается стандартными средствами игры.",
    [SI_BAV_PANEL_INTRO] = "|c6FCB9FАдаптивное управление камерой|r для ситуаций, когда ESO обычно ограничивает зум. Bureau of Acceptable Views делает переход между видом от первого и от третьего лица более предсказуемым, плавным и удобным.",
    [SI_BAV_PANEL_OVERVIEW] = "|c8C8A82• Работает верхом, в воде и в особых формах\n• Запоминает предпочитаемую дистанцию от третьего лица\n• Может сохранять вид от первого лица между релогами и сменой зон\n• Поддерживает быструю настройку через чат-команды|r",
    [SI_BAV_PANEL_TIPS] = "|cC5C29EБыстрый доступ|r\nИспользуйте |cFFFFFF/bav|r для статуса, |cFFFFFF/bav settings|r чтобы открыть эту панель, |cFFFFFF/bav config|r для настройки в чате и |cFFFFFF/bav help|r для полного списка команд.",
    [SI_BAV_HEADER_CAMERA] = "|cC5C29EТонкая настройка камеры|r",
    [SI_BAV_HEADER_BEHAVIOR] = "|cC5C29EПоведение и сохранение|r",
    [SI_BAV_HEADER_DEBUG] = "|cC5C29EДиагностика|r",
    [SI_BAV_SECTION_CAMERA_DESCRIPTION] = "|c8C8A82Настройте, насколько плавно и быстро ощущается зум, и задайте безопасную резервную дистанцию от третьего лица.|r",
    [SI_BAV_SECTION_BEHAVIOR_DESCRIPTION] = "|c8C8A82Определите, как аддон должен восстанавливать камеру после релогов, смены зон и возврата из первого лица.|r",
    [SI_BAV_SECTION_DEBUG_DESCRIPTION] = "|c8C8A82Полезно для проверки редких случаев и диагностики странного поведения камеры. Для обычной игры лучше держать уровень ниже, чтобы не засорять чат.|r",
    [SI_BAV_HEADER_DYNAMIC_FOV] = "Динамическое поле зрения",
    [SI_BAV_SECTION_DYNAMIC_FOV_DESCRIPTION] = "|c8C8A82Слегка расширяет или сужает поле зрения от третьего лица в зависимости от того, насколько вы отдалили камеру, создавая более кинематографичное ощущение глубины. |r|c6FCB9FВключено по умолчанию.|r",
    [SI_BAV_HEADER_CONTEXT_PRESETS] = "Контекстные пресеты",
    [SI_BAV_SECTION_CONTEXT_PRESETS_DESCRIPTION] = "|c8C8A82Автоматически подстраивают кадрирование камеры под конкретные игровые состояния. Каждое состояние включается отдельно, а общая сила эффекта масштабируется ползунком интенсивности. |r|cD0905EПо умолчанию отключено.|r",
    [SI_BAV_PANEL_FOOTER] = "|c6FCB9FПримечание:|r изменения слайдеров и переключателей сразу нормализуются и сохраняются.",
    [SI_BAV_SLASH_HINT] = "|cC5C29EБыстрые команды|r: |cFFFFFF/bav|r  |cC5C29E•|r  |cFFFFFF/bav settings|r  |cC5C29E•|r  |cFFFFFF/bav config|r  |cC5C29E•|r  |cFFFFFF/bav help|r",

    [SI_BAV_STATUS_TITLE] = "|cC5C29EТекущее состояние|r",
    [SI_BAV_STATUS_ON] = "вкл",
    [SI_BAV_STATUS_OFF] = "выкл",
    [SI_BAV_STATUS_CAM_FIRST_PERSON] = "от первого лица",
    [SI_BAV_STATUS_CAM_THIRD_PERSON] = "от третьего лица",
    [SI_BAV_STATUS_SHOULDER_AUTO] = "авто",
    [SI_BAV_STATUS_SHOULDER_MANUAL] = "вручную",
    [SI_BAV_STATUS_LABEL_CAMERA] = "Камера:",
    [SI_BAV_STATUS_LABEL_DYNAMIC_FOV] = "Динамический FOV:",
    [SI_BAV_STATUS_LABEL_VELOCITY_FOV] = "FOV от скорости:",
    [SI_BAV_STATUS_LABEL_PRESETS] = "Контекстные пресеты:",
    [SI_BAV_STATUS_LABEL_SHOULDER] = "Камера через плечо:",

    [SI_BAV_SETTING_ZOOM_STEP_NAME] = "Шаг зума",
    [SI_BAV_SETTING_ZOOM_STEP_TOOLTIP] = "Насколько меняется зум за одно действие. Меньшие значения ощущаются плавнее, большие - быстрее.",
    [SI_BAV_SETTING_THRESHOLD_NAME] = "Порог сохранения зума",
    [SI_BAV_SETTING_THRESHOLD_TOOLTIP] = "Только значения зума от третьего лица выше этого порога запоминаются как предпочтительная дистанция возврата из вида от первого лица.",
    [SI_BAV_SETTING_MIN_MOUNTED_NAME] = "Резервный зум от третьего лица",
    [SI_BAV_SETTING_MIN_MOUNTED_TOOLTIP] = "Резервная дистанция от третьего лица, используемая, когда нет корректного запомненного значения.",
    [SI_BAV_SETTING_PRESERVE_FPV_NAME] = "Сохранять вид от первого лица между релогами и зонами",
    [SI_BAV_SETTING_PRESERVE_FPV_TOOLTIP] = "Если включено, выход из игры или смена зоны в виде от первого лица восстановят его после загрузки. Если выключено, аддон вместо этого вернёт сохранённую дистанцию от третьего лица.",
    [SI_BAV_SETTING_DEBUG_MODE_NAME] = "Режим отладки",
    [SI_BAV_SETTING_DEBUG_MODE_TOOLTIP] = "Управляет объёмом диагностических сообщений, которые аддон выводит в чат.",
    [SI_BAV_SETTING_RESET_CONFIG_NAME] = "Сбросить к нейтральной камере",
    [SI_BAV_SETTING_RESET_CONFIG_TOOLTIP] = "Восстановить основные значения зума и выключить все необязательные функции - для чистой, «ванильной» камеры. Учтите: это не то же самое, что свежая установка - динамический FOV и FOV от скорости поставляются включёнными, но сброс намеренно их выключает, давая вам нейтральную отправную точку.",
    [SI_BAV_SETTING_RESET_CONFIG_CONFIRM] = "Будут восстановлены основные значения зума и выключены все необязательные функции (динамический FOV, FOV от скорости, контекстные пресеты, камера через плечо). Ваши изменения будут потеряны. Продолжить?",
    [SI_BAV_SETTING_RESET_CAMERA_NAME] = "Сбросить состояние камеры",
    [SI_BAV_SETTING_RESET_CAMERA_TOOLTIP] = "Немедленно вернуть управление камерой вам: снять активный контекстный пресет и удержание угла обзора, восстановить ваш исходный кадр и сбросить активное и сохранённое состояние камеры, используя текущий резервный зум.",
    [SI_BAV_SETTING_RESET_CAMERA_CONFIRM] = "Активный пресет и удержание угла обзора будут сняты, а камера сброшена к текущему резервному зуму. Продолжить?",
    [SI_BAV_SETTING_RESET_CAMERA_NOTE] = "|c6FCB9FСтраховка:|r воспринимайте это как ремень безопасности. Аддон очень надёжно работает с настройками и не должен оставлять камеру в некорректном состоянии, так что, скорее всего, это вам никогда не понадобится. Кнопка здесь исключительно ради тех самых 0.001% вероятности - один клик мгновенно вернёт вам полный контроль над камерой.",
    [SI_BAV_SETTING_PRINT_CONFIG_NAME] = "Показать текущую конфигурацию",
    [SI_BAV_SETTING_PRINT_CONFIG_TOOLTIP] = "Вывести текущую конфигурацию аддона в чат.",
    [SI_BAV_HEADER_CONFIGURATION] = "|cC5C29EКонфигурация|r",
    [SI_BAV_SECTION_CONFIGURATION_DESCRIPTION] = "|c8C8A82Просмотрите текущие настройки или сбросьте к нейтральной камере: основные значения зума восстанавливаются, а все необязательные функции выключаются. Сброс затрагивает только конфигурацию аддона и не трогает активную камеру.|r",
    [SI_BAV_HEADER_CAMERA_ACTIONS] = "|cC5C29EУправление камерой|r",
    [SI_BAV_SECTION_CAMERA_ACTIONS_DESCRIPTION] = "|c8C8A82Верните себе управление активной камерой одним кликом, независимо от сохранённой конфигурации.|r",
    [SI_BAV_SETTING_SELFCHECK_NAME] = "Запустить самопроверку",
    [SI_BAV_SETTING_SELFCHECK_TOOLTIP] = "Запустить проверку надёжности сейчас: проверить внутренние инварианты аддона и вывести в чат объём занимаемых им данных. В отличие от автоматического тихого прохода, исправное состояние тоже отображается.",
    [SI_BAV_SETTING_DUMP_STATE_NAME] = "Полный дамп состояния",
    [SI_BAV_SETTING_DUMP_STATE_TOOLTIP] = "Вывести в чат полный снимок текущего состояния камеры и игрока - для диагностики или отчётов об ошибках.",
    [SI_BAV_SETTING_CONFLICT_ADVISORY_NAME] = "Предупреждение о конфликте в чат",
    [SI_BAV_SETTING_CONFLICT_ADVISORY_TOOLTIP] = "Если другой аддон заставляет камеру быстро переключать вид, BAV отступает со своей обработкой, чтобы разорвать петлю. Когда опция включена, в чат также выводится однократное нейтральное уведомление. Сама защита работает всегда; эта опция управляет только сообщением в чате.",

    [SI_BAV_SETTING_DYNAMIC_FOV_ENABLED_NAME] = "Включить динамическое поле зрения",
    [SI_BAV_SETTING_DYNAMIC_FOV_ENABLED_TOOLTIP] = "Если включено, поле зрения от третьего лица плавно меняется между ближним и дальним значением по мере приближения и отдаления камеры.",
    [SI_BAV_SETTING_DYNAMIC_FOV_SMOOTH_NAME] = "Плавные переходы FOV",
    [SI_BAV_SETTING_DYNAMIC_FOV_SMOOTH_TOOLTIP] = "Если включено, поле зрения не переключается мгновенно между шагами зума, а плавно перетекает к новому значению за долю секунды. Когда вы приближаете или отдаляете камеру, объектив мягко «подъезжает» к целевому FOV по плавной кривой, а не дёргается рывком - это убирает резкие скачки картинки и делает зум заметно более кинематографичным и приятным для глаз. Целевое значение при этом всегда одно и то же: меняется только путь к нему, поэтому на итоговый кадр опция не влияет. Сам переход временный и не нагружает игру в простое.\n\n|c6FCB9FРекомендуется держать включённым:|r это заметно улучшает ощущение от камеры практически без какой-либо платы за производительность.",
    [SI_BAV_SETTING_DYNAMIC_FOV_NEAR_NAME] = "Поле зрения (камера приближена)",
    [SI_BAV_SETTING_DYNAMIC_FOV_NEAR_TOOLTIP] = "Поле зрения, применяемое когда камера приближена до упора. Ограничено допустимым диапазоном FOV движка, поэтому любое значение здесь безопасно.",
    [SI_BAV_SETTING_DYNAMIC_FOV_FAR_NAME] = "Поле зрения (камера отдалена)",
    [SI_BAV_SETTING_DYNAMIC_FOV_FAR_TOOLTIP] = "Поле зрения, применяемое когда камера отдалена до упора. Разведите его дальше от значения приближения для более сильного эффекта, сведите ближе чтобы смягчить, или сделайте равными чтобы полностью убрать эффект.",
    [SI_BAV_SETTING_DYNAMIC_FOV_RESET_NAME] = "Сбросить диапазон FOV",
    [SI_BAV_SETTING_DYNAMIC_FOV_RESET_TOOLTIP] = "Очистить ваши значения ближнего/дальнего FOV и вернуться к стандартному диапазону поля зрения движка.",
    [SI_BAV_SETTING_PRESETS_ENABLED_NAME] = "Включить контекстные пресеты",
    [SI_BAV_SETTING_PRESETS_ENABLED_TOOLTIP] = "Главный переключатель контекстных пресетов. Когда выключен, ни одна из настроек кадрирования по состояниям ниже не применяется.",
    [SI_BAV_LABEL_PRESET_STATES] = "|cC5C29EВыберите стиль для каждого состояния|r",
    [SI_BAV_LABEL_PRESET_STATES_HELP] = "|c8C8A82Выберите «Выключено», чтобы отключить состояние; ползунок интенсивности влияет только на состояния с непустым стилем.|r",
    [SI_BAV_SETTING_PRESET_INTENSITY_NAME] = "Интенсивность пресетов",
    [SI_BAV_SETTING_PRESET_INTENSITY_TOOLTIP] = "Масштабирует, насколько сильно активные пресеты смещают камеру: от 0% (без эффекта) до 100% (полный эффект).",
    [SI_BAV_SETTING_PRESET_STATE_INTENSITY_NAME] = "Интенсивность состояния",
    [SI_BAV_SETTING_PRESET_STATE_INTENSITY_TOOLTIP] = "Масштабирует кадрирование этого состояния поверх общей интенсивности пресетов: от 0% (без эффекта) до 100% (полная сила стиля). Недоступно, когда стиль этого состояния - «Выкл».",
    [SI_BAV_SETTING_PRESET_COALESCE_NAME] = "Задержка возврата",
    [SI_BAV_SETTING_PRESET_COALESCE_TOOLTIP] = "Сколько времени выход из этого состояния ждёт перед возвратом камеры. Небольшая задержка позволяет быстрому выходу-и-возврату (например, бой закончился и тут же начался снова) свестись к нулевому действию вместо рывка камеры. «Выкл» возвращает камеру сразу, без сглаживания. По умолчанию отключено для всех состояний.",
    [SI_BAV_SETTING_PRESET_COALESCE_OFF] = "Выкл",
    [SI_BAV_SETTING_PRESET_COALESCE_MS_FORMAT] = "%d мс",
    [SI_BAV_SETTING_PRESET_COALESCE_S_FORMAT] = "%g с",
    [SI_BAV_SETTING_PRESET_SMOOTH_NAME] = "Плавные переходы пресетов",
    [SI_BAV_SETTING_PRESET_SMOOTH_TOOLTIP] = "Если включено, переключение контекстных пресетов плавно перетекает между кадрированием камеры и полем зрения за долю секунды вместо мгновенного скачка. Чисто косметическая опция.",
    [SI_BAV_SETTING_PRESET_STATE_COMBAT_NAME] = "Бой",
    [SI_BAV_SETTING_PRESET_STATE_COMBAT_TOOLTIP] = "Применять пресет кадрирования для боя, пока вы в бою.",
    [SI_BAV_SETTING_PRESET_STATE_WEREWOLF_NAME] = "Вервольф",
    [SI_BAV_SETTING_PRESET_STATE_WEREWOLF_TOOLTIP] = "Применять пресет кадрирования для вервольфа, пока вы в форме.",
    [SI_BAV_SETTING_PRESET_STATE_STEALTH_NAME] = "Скрытность",
    [SI_BAV_SETTING_PRESET_STATE_STEALTH_TOOLTIP] = "Применять пресет кадрирования для скрытности, пока вы крадётесь или скрыты.",
    [SI_BAV_SETTING_PRESET_STATE_INTERACTION_NAME] = "Взаимодействие",
    [SI_BAV_SETTING_PRESET_STATE_INTERACTION_TOOLTIP] = "Применять пресет кадрирования для взаимодействия, пока вы говорите с NPC или ведёте диалог.",
    [SI_BAV_SETTING_PRESET_STATE_MOUNTED_NAME] = "Верхом",
    [SI_BAV_SETTING_PRESET_STATE_MOUNTED_TOOLTIP] = "Применять пресет кадрирования для езды верхом.",
    [SI_BAV_SETTING_PRESET_STATE_SWIMMING_NAME] = "Плавание",
    [SI_BAV_SETTING_PRESET_STATE_SWIMMING_TOOLTIP] = "Применять пресет кадрирования во время плавания.",
    [SI_BAV_SETTING_PRESET_STATE_SPRINT_NAME] = "Спринт",
    [SI_BAV_SETTING_PRESET_STATE_SPRINT_TOOLTIP] = "Применять пресет кадрирования для спринта при беге пешком.",

    [SI_BAV_SETTING_PRESET_STYLE_OFF_NAME] = "Выключено",
    [SI_BAV_SETTING_PRESET_STYLE_SUBTLE_NAME] = "Сдержанный",
    [SI_BAV_SETTING_PRESET_STYLE_CINEMATIC_NAME] = "Кинематографичный",
    [SI_BAV_SETTING_PRESET_STYLE_ACTION_NAME] = "Динамичный",

    [SI_BAV_HEADER_SHOULDER] = "Камера через плечо",
    [SI_BAV_SECTION_SHOULDER_DESCRIPTION] = "|c8C8A82Смещает камеру от третьего лица за одно плечо для сфокусированного кинематографичного кадра. Выберите способ срабатывания: |r|c6FCB9FАвто|r|c8C8A82 смещает автоматически в выбранных состояниях; |r|c6FCB9FВручную|r|c8C8A82 смещает по команде |cFFFFFF/bav shoulder|r|c8C8A82. Пока опция включена, она перехватывает плечо у пресета скрытности. |r|cD0905EПо умолчанию отключено.|r",
    [SI_BAV_SETTING_SHOULDER_MODE_NAME] = "Режим плеча",
    [SI_BAV_SETTING_SHOULDER_MODE_TOOLTIP] = "«Выкл» отключает функцию. «Авто» автоматически смещает камеру за выбранное плечо, пока вы находитесь в любом из выбранных состояний. «Вручную» позволяет смещать камеру по команде /bav shoulder (автоматическое поведение при этом отключено). Два активных режима взаимоисключающие.",
    [SI_BAV_SETTING_SHOULDER_MODE_OFF] = "Выкл",
    [SI_BAV_SETTING_SHOULDER_MODE_AUTO] = "Авто (по состоянию)",
    [SI_BAV_SETTING_SHOULDER_MODE_MANUAL] = "Вручную (/bav shoulder)",
    [SI_BAV_SETTING_SHOULDER_OFFSET_NAME] = "Смещение плеча",
    [SI_BAV_SETTING_SHOULDER_OFFSET_TOOLTIP] = "Насколько камера смещается в сторону: от 0% (по центру) до 100% (полностью через плечо). Движок ограничивает результат допустимым диапазоном.",
    [SI_BAV_SETTING_SHOULDER_SIDE_NAME] = "Сторона (Авто)",
    [SI_BAV_SETTING_SHOULDER_SIDE_TOOLTIP] = "За какое плечо смещается камера в режиме «Авто».",
    [SI_BAV_SETTING_SHOULDER_SIDE_LEFT] = "Левое",
    [SI_BAV_SETTING_SHOULDER_SIDE_RIGHT] = "Правое",
    [SI_BAV_SETTING_SHOULDER_SIDE_CENTER] = "По центру",
    [SI_BAV_SETTING_SHOULDER_AUTO_STATES_LABEL] = "|cC5C29EСмещать автоматически в этих состояниях|r",
    [SI_BAV_SETTING_SHOULDER_AUTO_HELP] = "|c8C8A82Камера смещается за выбранную сторону, пока вы в любом отмеченном состоянии, и возвращается по центру, когда вы выходите из всех них.|r",
    [SI_BAV_SETTING_SHOULDER_STATE_COMBAT_TOOLTIP] = "Смещать камеру за плечо, пока вы в бою.",
    [SI_BAV_SETTING_SHOULDER_STATE_STEALTH_TOOLTIP] = "Смещать камеру за плечо, пока вы крадётесь или скрыты.",
    [SI_BAV_SETTING_SHOULDER_STATE_MOUNTED_TOOLTIP] = "Смещать камеру за плечо во время езды верхом.",
    [SI_BAV_SETTING_SHOULDER_STATE_SWIMMING_TOOLTIP] = "Смещать камеру за плечо во время плавания.",
    [SI_BAV_SETTING_SHOULDER_STATE_SPRINT_TOOLTIP] = "Смещать камеру за плечо при беге пешком.",

    [SI_BAV_HEADER_VELOCITY_FOV] = "Поле зрения от скорости",
    [SI_BAV_SECTION_VELOCITY_FOV_HOW] = "|cC5C29EКак это работает вместе с другими функциями|r\n|c8C8A82• Прибавка от скорости |rдобавляется поверх|c8C8A82 динамического FOV (от зума) - они складываются, а не конфликтуют.\n• Если контекстный пресет фиксирует FOV для текущего состояния (например «Бой» или «Спринт»), |rприоритет у пресета|c8C8A82 - прибавка от скорости приостанавливается, пока вы в этом состоянии, и возвращается, когда вы из него выходите.\n• Считывается ваша настоящая скорость движения, поэтому спринт, маунт, плавание и баффы скорости питают один и тот же эффект - настраивать что-то по состояниям не нужно.|r",
    [SI_BAV_SECTION_VELOCITY_FOV_DESCRIPTION] = "|c8C8A82Расширяет поле зрения тем сильнее, чем быстрее вы реально движетесь - спринт, верхом, вплавь или под любым баффом скорости - создавая кинематографичное ощущение скорости, и плавно возвращает его при замедлении. Считывает вашу настоящую скорость движения, поэтому реагирует на любой источник. Добавляется поверх динамического FOV и работает самостоятельно, когда динамический FOV выключен. |r|c6FCB9FВключено по умолчанию.|r",
    [SI_BAV_SETTING_VELOCITY_FOV_ENABLED_NAME] = "Включить поле зрения от скорости",
    [SI_BAV_SETTING_VELOCITY_FOV_ENABLED_TOOLTIP] = "Если включено, поле зрения от третьего лица плавно расширяется тем сильнее, чем быстрее вы движетесь, и плавно возвращается при замедлении.",
    [SI_BAV_SETTING_VELOCITY_FOV_DEBUG_NAME] = "Показать отладочный оверлей",
    [SI_BAV_SETTING_VELOCITY_FOV_DEBUG_TOOLTIP] = "Показывает на экране небольшую сводку: вашу текущую скорость движения, текущую прибавку и позицию - удобно для калибровки эффекта. Выводится только на экран, никогда в чат, и может оставаться включённым независимо от самого эффекта. По умолчанию отключено.",
    [SI_BAV_SETTING_VELOCITY_FOV_SENSITIVITY_NAME] = "Чувствительность",
    [SI_BAV_SETTING_VELOCITY_FOV_SENSITIVITY_TOOLTIP] = "Насколько сильно поле зрения расширяется на скорости: от 0% (без изменения) до 100% (самое сильное расширение). Движок ограничивает итоговый FOV допустимым диапазоном.",

    [SI_BAV_DEBUG_LEVEL_OFF] = "Выключено",
    [SI_BAV_DEBUG_LEVEL_ERRORS] = "Ошибки",
    [SI_BAV_DEBUG_LEVEL_WARNINGS] = "Предупреждения",
    [SI_BAV_DEBUG_LEVEL_INFO] = "Информация",
    [SI_BAV_DEBUG_LEVEL_VERBOSE] = "Подробно",

    [SI_BAV_BOOL_TRUE] = "да",
    [SI_BAV_BOOL_FALSE] = "нет",

    [SI_BAV_LOG_LEVEL_ERROR] = "[ОШИБКА]",
    [SI_BAV_LOG_LEVEL_WARN] = "[ПРЕДУПРЕЖДЕНИЕ]",
    [SI_BAV_LOG_LEVEL_INFO] = "[ИНФО]",
    [SI_BAV_LOG_LEVEL_DEBUG] = "[ОТЛАДКА]",

    [SI_BAV_SOURCE_TOGGLE_FPV] = "Переключение FPV",
    [SI_BAV_SOURCE_ZOOM_IN] = "Приблизить",
    [SI_BAV_SOURCE_ZOOM_OUT] = "Отдалить",

    [SI_BAV_LOG_INVALID_ZOOM] = "SetCameraZoom: Некорректное значение зума: %s",
    [SI_BAV_LOG_SET_FAILED] = "SetCameraZoom завершился ошибкой: %s",
    [SI_BAV_LOG_SET_APPLY_FAILED] = "SetCameraZoom: Не удалось применить запрошенный зум=%.2f",
    [SI_BAV_LOG_SET_APPLIED] = "SetCameraZoom: применён запрошенный зум=%.2f",
    [SI_BAV_LOG_TOGGLE_BLOCKED_REENTRANT] = "ToggleFPV: Заблокировано (повторный вход)",
    [SI_BAV_LOG_TOGGLE_PAIR_PASS] = "ToggleFPV: Парный тогл в том же кадре - передаём игре",
    [SI_BAV_LOG_TOGGLE_PAIR_UNDO] = "ToggleFPV: Парный тогл в том же кадре - откатываем своё изменение, чтобы пара осталась сбалансированной",
    [SI_BAV_LOG_OSCILLATION_BACKOFF] = "ToggleFPV: Обнаружена неуправляемая осцилляция вида - хук FPV переведён в пассивный режим до /bav reset или перезахода",
    [SI_BAV_LOG_TOGGLE_PAIR_UNDO_FAILED] = "ToggleFPV: Движок отклонил откат в том же кадре - передаём парный тогл игре, чтобы она сбалансировала свою пару",
    [SI_BAV_LOG_TOGGLE_SIEGE_PASS] = "ToggleFPV: Управление осадным орудием - передаём игре",
    [SI_BAV_LOG_TOGGLE_STATE] = "ToggleFPV: zoom=%.2f, isLimited=%s, lastZoom=%.2f",
    [SI_BAV_LOG_TOGGLE_TO_THIRD] = "ToggleFPV: FPV -> Third Person (цель=%.2f)",
    [SI_BAV_LOG_TOGGLE_TO_FPV] = "ToggleFPV: Third Person -> FPV (было=%.2f)",
    [SI_BAV_LOG_TOGGLE_HANDLED] = "ToggleFPV: Обработано аддоном",
    [SI_BAV_LOG_TOGGLE_PASSING] = "ToggleFPV: Передаём игре (обычный зум)",
    [SI_BAV_LOG_TOGGLE_UNHANDLED_ERROR] = "ToggleFPV: Необработанная ошибка: %s",
    [SI_BAV_LOG_SOURCE_CALLED] = "%s: Вызов",
    [SI_BAV_LOG_SOURCE_SIEGE_PASS] = "%s: Управление осадным орудием - передаём игре",
    [SI_BAV_LOG_SOURCE_ALREADY_AT_FPV] = "%s: Уже в FPV (%.2f) - блокируем",
    [SI_BAV_LOG_SOURCE_ALREADY_AT_MAX] = "%s: Уже на максимуме (%.2f) - блокируем",
    [SI_BAV_LOG_SOURCE_TRANSITION] = "%s: %.2f -> %.2f",
    [SI_BAV_LOG_SOURCE_SET_FAILED] = "%s: Установка аддоном не удалась, передаём игре",
    [SI_BAV_LOG_SOURCE_UPDATED_LASTZOOM] = "%s: Обновлён lastZoom=%.2f",
    [SI_BAV_LOG_SOURCE_PRESERVING_LASTZOOM] = "%s: Сохраняем lastZoom=%.2f (ниже порога)",
    [SI_BAV_LOG_INVALID_SAVED_CURRENT_FALLBACK] = "GetRestoredCurrentZoom: Некорректный saved currentZoom=%s, используем lastThirdPersonZoom",
    [SI_BAV_LOG_INITIALIZE_LAST_FROM_SAVED_TP] = "InitializeLastZoom: lastZoom взят из saved lastThirdPersonZoom=%.2f",
    [SI_BAV_LOG_INITIALIZE_LAST_FROM_CURRENT] = "InitializeLastZoom: lastZoom взят из текущего игрового зума=%.2f",
    [SI_BAV_LOG_INITIALIZE_LAST_FROM_SAVED_CURRENT] = "InitializeLastZoom: lastZoom взят из saved currentZoom=%.2f",
    [SI_BAV_LOG_INITIALIZE_LAST_DEFAULT] = "InitializeLastZoom: lastZoom установлен по умолчанию=%.2f",
    [SI_BAV_LOG_ONPLAYERACTIVATED_REAPPLY] = "OnPlayerActivated: Повторно применяем состояние камеры в мире",
    [SI_BAV_LOG_APPLYING_SAVED_STATE] = "OnPlayerActivated: Применяем currentZoom=%.2f, lastThirdPersonZoom=%.2f",
    [SI_BAV_LOG_FAILED_APPLY_SAVED_STATE] = "OnPlayerActivated: Не удалось применить currentZoom=%.2f",
    [SI_BAV_LOG_INVALID_SAVED_STATE] = "OnPlayerActivated: Некорректное сохранённое состояние current=%s, lastThirdPerson=%s",
    [SI_BAV_LOG_ONPLAYERDEACTIVATED_SAVING] = "OnPlayerDeactivated: Сохраняем состояние перед выходом/сменой зоны",
    [SI_BAV_LOG_ONADDONLOADED_LOADING] = "OnAddonLoaded: Загрузка аддона v%s...",
    [SI_BAV_LOG_MIGRATED_LEGACY_ZOOM] = "OnAddonLoaded: Выполнена миграция legacy zoom=%.2f в разделённое состояние камеры",
    [SI_BAV_LOG_MIGRATED_LEGACY_SAVEDVARS] = "OnAddonLoaded: Выполнена миграция сохранённых данных из %s",
    [SI_BAV_LOG_CURRENT_GAME_ZOOM] = "OnAddonLoaded: Текущий зум игры=%.2f",
    [SI_BAV_LOG_SAVEDVARS_INITIALIZED] = "OnAddonLoaded: SavedVars инициализированы, currentZoom=%.2f, lastThirdPersonZoom=%.2f",
    [SI_BAV_LOG_CONFIG_INITIALIZED] = "OnAddonLoaded: Конфигурация step=%.2f, threshold=%.2f, minMounted=%.2f, preserveFPV=%s",
    [SI_BAV_LOG_GAMEPAD_DOWN_UNAVAILABLE] = "OnAddonLoaded: GameCameraGamepadZoomDown недоступен - используется стандартная обработка контроллера игрой",
    [SI_BAV_LOG_GAMEPAD_UP_UNAVAILABLE] = "OnAddonLoaded: GameCameraGamepadZoomUp недоступен - используется стандартная обработка контроллера игрой",
    [SI_BAV_LOG_GAMEPAD_DOWN_HOOKED] = "OnAddonLoaded: GameCameraGamepadZoomDown успешно подключён",
    [SI_BAV_LOG_GAMEPAD_UP_HOOKED] = "OnAddonLoaded: GameCameraGamepadZoomUp успешно подключён",
    [SI_BAV_LOG_HOOKS_REGISTERED] = "OnAddonLoaded: Хуки зарегистрированы",
    [SI_BAV_LOG_ADDON_LOADED] = "OnAddonLoaded: Аддон успешно загружен",
    [SI_BAV_LOG_LAM_MISSING] = "LibAddonMenu-2.0 не найден. Панель настроек недоступна, но slash-команды продолжат работать.",

    [SI_BAV_MSG_FULL_STATE_DUMP] = "========== ПОЛНЫЙ ДАМП СОСТОЯНИЯ ==========",
    [SI_BAV_MSG_CONFLICT_ADVISORY] = "BAV заметил частое переключение вида камеры между первым и третьим лицом. Обычно это взаимодействие между аддонами. BAV отступил со своей обработкой вида, чтобы прекратить мерцание (до перезахода или /bav reset). Если мерцание продолжится - попробуйте отключать другие аддоны по одному, чтобы найти источник. Детали: /bav selfcheck.",
    [SI_BAV_MSG_VERSION_DEBUG] = "Версия: %s | Отладка: %s (%d)",
    [SI_BAV_MSG_ZOOM_VALUES] = "--- Значения зума ---",
    [SI_BAV_MSG_CURRENT_SAVED] = "Текущий: %.2f | Last: %.2f | SavedCurrent: %.2f | SavedLastTP: %.2f",
    [SI_BAV_MSG_LIMITS] = "FPV: %d | Max: %.1f | Step: %.2f",
    [SI_BAV_MSG_BEHAVIOR_CONFIG] = "MinMounted: %.2f | Threshold: %.2f | PreserveFPV: %s",
    [SI_BAV_MSG_PLAYER_STATE] = "--- Состояние персонажа ---",
    [SI_BAV_MSG_PLAYER_STATE_VALUES] = "FPV: %s | Mounted: %s | Werewolf: %s | Swimming: %s | Siege: %s",
    [SI_BAV_MSG_ZOOM_LIMITED] = "Зум ограничен: %s",
    [SI_BAV_MSG_PROTECTION_FLAGS] = "--- Флаги защиты ---",
    [SI_BAV_MSG_PROTECTION_FLAGS_VALUES] = "isTogglingFPV: %s | saveQueued: %s",
    [SI_BAV_MSG_SCENARIO] = "--- Сценарий: %s ---",
    [SI_BAV_MSG_CURRENT_ZOOM_FPV] = "Текущий зум: %.2f (FPV=%s)",
    [SI_BAV_MSG_WOULD_RESTORE_TO] = "Будет восстановлено: %.2f",
    [SI_BAV_MSG_WOULD_SAVE_LASTZOOM] = "Будет сохранён lastZoom: %.2f",
    [SI_BAV_MSG_WOULD_SET_ZOOM_TO_FPV] = "Зум будет установлен в: %d (FPV)",
    [SI_BAV_MSG_ZOOM_TRANSITION] = "Зум: %.2f -> %.2f",
    [SI_BAV_MSG_WOULD_UPDATE_LASTZOOM] = "lastZoom будет обновлён: %s",
    [SI_BAV_MSG_ALREADY_AT_FPV] = "Уже в FPV - будет заблокировано",
    [SI_BAV_MSG_ALREADY_AT_MAX] = "Уже на максимуме - будет заблокировано",
    [SI_BAV_MSG_IS_MOUNTED] = "На маунте: %s",
    [SI_BAV_MSG_IS_LIMITED] = "Ограниченное состояние: %s",
    [SI_BAV_MSG_TOGGLE_HANDLED] = "Переключение будет обработано аддоном (ограниченное состояние)",
    [SI_BAV_MSG_TOGGLE_GAME] = "Переключение будет передано игре (обычное состояние)",
    [SI_BAV_MSG_FPV_RECOVERY] = "Если переключить из FPV сейчас, будет восстановлено: %.2f",
    [SI_BAV_MSG_LASTZOOM_VALIDITY] = "Валидность lastZoom: valid=%s, >FPV=%s",
    [SI_BAV_MSG_PRESERVE_FPV_STATE] = "Сохранять FPV между зонами: %s",
    [SI_BAV_MSG_CURRENTZOOM_WOULD_BECOME] = "При сохранении сейчас currentZoom станет: %.2f",
    [SI_BAV_MSG_FPV_REPLACED_ON_RELOG] = "FPV будет заменён сохранённым зумом от третьего лица при релоге/смене зоны",
    [SI_BAV_MSG_UNKNOWN_SCENARIO] = "Неизвестный сценарий. Используйте: toggle-fpv, zoom-in, zoom-out, mounted-toggle, fpv-recovery, relog-fpv",

    [SI_BAV_MSG_DEBUG_MODE_SET] = "Режим отладки: %s (%d)",
    [SI_BAV_MSG_INVALID_DEBUG_LEVEL] = "Некорректный уровень. Используйте 0-4",
    [SI_BAV_MSG_CONFIG_SUMMARY] = "Конфиг | Step: %.2f | Threshold: %.2f | MinMounted: %.2f | PreserveFPV: %s",
    [SI_BAV_MSG_CONFIG_USAGE] = "Использование: /bav config step <value> | threshold <value> | minmounted <value> | preservefpv <on/off> | reset",
    [SI_BAV_MSG_CONFIG_RESET] = "Конфигурация сброшена к значениям по умолчанию",
    [SI_BAV_MSG_CONFIG_STEP_SET] = "zoomStep установлен в %.2f",
    [SI_BAV_MSG_CONFIG_THRESHOLD_SET] = "lastZoomThreshold установлен в %.2f",
    [SI_BAV_MSG_CONFIG_MINMOUNTED_SET] = "zoomMinMounted установлен в %.2f",
    [SI_BAV_MSG_CONFIG_PRESERVE_SET] = "preserveFpvBetweenZones установлен в %s",
    [SI_BAV_MSG_CONFIG_UNKNOWN_OPTION] = "Неизвестная опция config. Используйте: step, threshold, minmounted, preservefpv, reset",
    [SI_BAV_MSG_USAGE_SET] = "Использование: /bav set <value>",
    [SI_BAV_MSG_USAGE_CONFIG_STEP] = "Использование: /bav config step <value>",
    [SI_BAV_MSG_USAGE_CONFIG_THRESHOLD] = "Использование: /bav config threshold <value>",
    [SI_BAV_MSG_USAGE_CONFIG_MINMOUNTED] = "Использование: /bav config minmounted <value>",
    [SI_BAV_MSG_USAGE_CONFIG_PRESERVEFPV] = "Использование: /bav config preservefpv <on|off>",
    [SI_BAV_MSG_ZOOM_SET] = "Зум установлен в: %.2f",
    [SI_BAV_MSG_LASTZOOM_UPDATED] = "lastZoom обновлён: %.2f",
    [SI_BAV_MSG_SET_FAILED] = "Не удалось установить зум: %.2f (допустимый диапазон: %d-%d)",
    [SI_BAV_MSG_STATUS] = "Зум: %.2f | Last: %.2f | SavedCurrent: %.2f | SavedLastTP: %.2f | Отладка: %s (%d)",
    [SI_BAV_MSG_RESET_SUCCESS] = "Состояние камеры сброшено к %.2f с использованием текущей конфигурации",
    [SI_BAV_MSG_RESET_FAILED_SYNCED] = "Не удалось применить reset зума %.2f, но сохранённое состояние было обновлено синхронно",
    [SI_BAV_MSG_UNKNOWN_COMMAND] = "Неизвестная команда. Используйте /bav help",
    [SI_BAV_MSG_SETTINGS_UNAVAILABLE] = "Панель настроек недоступна (LibAddonMenu-2.0 не найдена). Используйте /bav config для настройки в чате.",
    [SI_BAV_MSG_SHOULDER_SET] = "Камера смещена: %s",
    [SI_BAV_MSG_SHOULDER_NOT_MANUAL] = "Смещение плеча не в ручном режиме. Переключите его на «Вручную» в /bav settings, чтобы использовать эту команду.",

    [SI_BAV_MSG_HELP_TITLE] = "=== Команды ===",
    [SI_BAV_MSG_HELP_STATUS] = "/bav - Показать краткий статус",
    [SI_BAV_MSG_HELP_SETTINGS] = "/bav settings - Открыть панель настроек (псевдонимы: ui, panel)",
    [SI_BAV_MSG_HELP_DUMP] = "/bav dump - Полный дамп состояния",
    [SI_BAV_MSG_HELP_DEBUG] = "/bav debug <0-4> - Установить уровень отладки",
    [SI_BAV_MSG_HELP_SET] = "/bav set <value> - Принудительно установить зум",
    [SI_BAV_MSG_HELP_CONFIG] = "/bav config - Показать текущую конфигурацию",
    [SI_BAV_MSG_HELP_CONFIG_STEP] = "/bav config step <value> - Изменить шаг зума",
    [SI_BAV_MSG_HELP_CONFIG_THRESHOLD] = "/bav config threshold <value> - Изменить порог lastZoom",
    [SI_BAV_MSG_HELP_CONFIG_MINMOUNTED] = "/bav config minmounted <value> - Изменить резервный зум от третьего лица",
    [SI_BAV_MSG_HELP_CONFIG_PRESERVEFPV] = "/bav config preservefpv <on|off> - Сохранять FPV между релогами и зонами",
    [SI_BAV_MSG_HELP_CONFIG_RESET] = "/bav config reset - Сбросить конфигурацию",
    [SI_BAV_MSG_HELP_SIMULATE] = "/bav simulate <scenario> - Симулировать сценарий",
    [SI_BAV_MSG_HELP_RESET] = "/bav reset - Сбросить состояние камеры по текущему конфигу",
    [SI_BAV_MSG_HELP_SCENARIOS] = "Сценарии: toggle-fpv, zoom-in, zoom-out, mounted-toggle, fpv-recovery, relog-fpv",
    [SI_BAV_MSG_HELP_SELFCHECK] = "/bav selfcheck - Проверка надёжности (инварианты + след памяти)",

    [SI_BAV_SELFCHECK_PROBLEM] = "Самопроверка: %s",
    [SI_BAV_SELFCHECK_ORPHANED_HOLD] = "FOV удерживается, но ни один пресет не активен (зависший hold). Если кадрирование застряло, используйте действие восстановления камеры.",
    [SI_BAV_SELFCHECK_SNAPSHOT_AT_DEFAULT] = "Снимок камеры сохранён, хотя ни один пресет не активен (устаревший снимок).",
    [SI_BAV_SELFCHECK_MISSING_SNAPSHOT] = "Активен пресет, но снимок для восстановления не был сделан.",
    [SI_BAV_SELFCHECK_SPRINT_POLL_LEAK] = "Опрос спринта работает, хотя пресеты спринта выключены (утечка таймера).",
    [SI_BAV_SELFCHECK_TRANSITION_LEAK] = "Плавный переход всё ещё выполняется, хотя пресеты выключены (утечка апдейтера).",
    [SI_BAV_SELFCHECK_FOV_GLIDE_LEAK] = "Плавный переход FOV всё ещё выполняется, хотя пресеты выключены (утечка апдейтера).",
    [SI_BAV_SELFCHECK_COALESCE_LEAK] = "Таймер объединения смен состояния всё ещё активен, хотя пресеты выключены (утечка таймера).",
    [SI_BAV_SELFCHECK_OPTIONS_OPEN_LEAK] = "Состояние окна настроек всё ещё отмечено открытым, хотя пресеты выключены (утечка состояния).",
    [SI_BAV_SELFCHECK_INTERACTION_ENTRY_LEAK] = "Таймер задержки входа в пресет взаимодействия всё ещё активен, хотя пресеты выключены (утечка таймера).",
    [SI_BAV_SELFCHECK_SHOULDER_POLL_LEAK] = "Опрос спринта для плеча работает, хотя смещение плеча выключено (утечка таймера).",
    [SI_BAV_SELFCHECK_SHOULDER_OWNERSHIP_LEAK] = "Базовое значение плеча сохранено, хотя смещение плеча выключено (утечка состояния).",
    [SI_BAV_SELFCHECK_SHOULDER_OPTIONS_LEAK] = "Состояние окна настроек всё ещё отмечено открытым, хотя смещение плеча выключено (утечка состояния).",
    [SI_BAV_SELFCHECK_VELOCITY_POLL_LEAK] = "Опрос спринта для FOV от скорости работает, хотя FOV от скорости выключено (утечка таймера).",
    [SI_BAV_SELFCHECK_VELOCITY_BOOST_LEAK] = "Прибавка FOV от скорости всё ещё применяется, хотя FOV от скорости выключено (утечка состояния).",
    [SI_BAV_SELFCHECK_DYNAMIC_MANUAL_BASE_LEAK] = "Заимствованное базовое значение FOV всё ещё удерживается, хотя динамический FOV простаивает (утечка состояния).",
    [SI_BAV_SELFCHECK_SLOT_LEAK] = "Число рабочих слотов камеры выросло до %d (возможная утечка).",
    [SI_BAV_SELFCHECK_FOOTPRINT_GROWTH] = "Данные самого BAV выросли на %d записей с прошлой проверки (сейчас %d). Возможна утечка.",
    [SI_BAV_SELFCHECK_FOOTPRINT_REPORT] = "След BAV: %d записей | с загрузки: %+d | с прошлой: %+d",
    [SI_BAV_SELFCHECK_ALL_OK] = "Все инварианты в норме.",
    [SI_BAV_SELFCHECK_BACKOFF_ACTIVE] = "Хук FPV переведён в пассивный режим после обнаружения быстрой осцилляции вида (%d переключений в окне). Используйте /bav reset или перезайдите, чтобы вернуть обычную обработку.",
    [SI_BAV_SELFCHECK_BACKOFF_INACTIVE] = "Хук FPV активен (осцилляция вида не обнаружена).",
    [SI_BAV_SELFCHECK_ZOOM_WRITE_FAILURES] = "Игра отклонила %d записей дистанции камеры подряд. Возможно, камерой управляет другая система (например, в облике трансформации). BAV отступил, чтобы вид не навязывался принудительно; если кадрирование выглядит неправильно - /bav reset или перезайдите.",

    [SI_BAV_SCENARIO_TOGGLE_FPV] = "toggle-fpv",
    [SI_BAV_SCENARIO_ZOOM_IN] = "zoom-in",
    [SI_BAV_SCENARIO_ZOOM_OUT] = "zoom-out",
    [SI_BAV_SCENARIO_MOUNTED_TOGGLE] = "mounted-toggle",
    [SI_BAV_SCENARIO_FPV_RECOVERY] = "fpv-recovery",
    [SI_BAV_SCENARIO_RELOG_FPV] = "relog-fpv",
}

for stringId, value in pairs(strings) do
    SafeAddString(stringId, value, 1)
end
